apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-scratch
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/upbound/configuration-scratch
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration is completely empty.
    meta.crossplane.io/readme: |
      This starter configuration is completely empty, allowing you to start
      entirely from scratch.
spec:
  crossplane:
    version: ">=v1.15.0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/platform-ref-aws
      version: "v1.1.0"
